### PR TITLE
Fix warning messages

### PR DESCRIPTION
**Pull request by marlomgirardi**
- Move `componentWillMount` content to `constructor` to avoid deprecation message.
- Update babel preset-env to remove `browserslist` update message.

### CODE REVIEW

**Comment by echenley** [comment]
@marlomgirardi Are you able to publish a new version with these changes to npm?

**Comment by marlomgirardi** [comment]
Sorry, I don't have access to this package on npm.
I believe just @davidtheclark / @tristen have.

**Comment by theoavoyne** [comment]
I'm using `4.0.1` and I'm still getting the warnings.

**Comment by echenley** [comment]
@theoavoyne Looks like it's coming from react-displace, which is a dependency of react-aria-modal.

https://github.com/davidtheclark/react-displace/pull/8
https://github.com/davidtheclark/react-displace/pull/9

**Pull request merged**
