### PR TITLE
Added option, `focusTrapActive`, to allow disabling the focus trap.

### PR DESCRIPTION
**Pull request by chaddjohnson**
Per https://github.com/davidtheclark/react-aria-modal/issues/101, I've added an option to disable the focus trap. Please consider merging this into mainstream. Thanks!

### CODE REVIEW

**Comment by chaddjohnson** [comment]
@nijynot Thanks. Is there anything else I need to do to get this merged into master?

**Comment by resource11** [comment]
Circling back here... One of the key tenets of an accessible modal is **trapping focus inside** the modal when it is open. I'm concerned that adding this feature in will create a plethora of inaccessible modals out there... :)

Here's a [great article on accessible modals by Ire Aderinokun](https://bitsofco.de/accessible-modal-dialog/) that describes the concept very well.

**Comment by marlomgirardi** [comment]
One of the project goals is accessibility, as @resource11 said, focus trap in a modal is a must-have.

**Comment by chaddjohnson** [comment]
> Circling back here... One of the key tenets of an accessible modal is **trapping focus inside** the modal when it is open. I'm concerned that adding this feature in will create a plethora of inaccessible modals out there... :)
> 
> Here's a [great article on accessible modals by Ire Aderinokun](https://bitsofco.de/accessible-modal-dialog/) that describes the concept very well.

There are valid use cases due disabling focus traps. For example, in my app, a modal is placed inline in a page in design mode (the user is designing a modal). In this case, no interaction with the modal takes place.

**Pull request closed without merging**
